package com.chnye.common.fsm;

public enum CodeEventType {
	NEWCONFIG,
	NEWCONFIG_COMPLETE,
	NEWCONFIG_ROLLBACK,
	MODIFYCONFIG,
	MODIFYCONFIG_COMPLETE,
	MODIFYCONFIG_ROLLBACK,
	DELETECONFIG,
	DELETECONFIG_COMPLETE,
	DELETECONFIG_ROLLBACK;
}
